#!/bin/sh
#SVNHOST="svn.freebsd.org"
SVNHOST="svn0.us-west.freebsd.org"
echo "Started:"
date;
PATH=$PATH:/usr/sbin
echo "Started: "
date +%c;
if [ -e "/usr/ports/.svn" ]; then
    cd /usr/ports/;
    /usr/local/bin/svn update;
else
    /usr/local/bin/svn checkout svn://$SVNHOST/ports/head /usr/ports;
fi;
#/usr/sbin/portsnap cron
if [ -x "/usr/local/bin/ezjail-admin" ]; then
    /usr/local/bin/ezjail-admin update -P
fi;
echo "Finished:"

date +%c;
